### PR TITLE
add support for lookbehind and negative lookbehind

### PR DESCRIPTION
**Pull request by luiz290788**

### CODE REVIEW

**Comment by luiz290788** [comment]
@bd82 any chance to have my PR merged? I would like to add support to lookbehind to avoid warnings in chevrotain

**Comment by bd82** [comment]
Hello @luiz290788 

I want to merge this package into the main Chevrotain's mono repo.
Perhaps it would be best to re-create and merge your PR after I've done so.
So:
1. it would be easier to test E2E.
2. no unneeded maintenance on a repo I intend to archive (e.g failing release process / updating build process).

**Comment by luiz290788** [comment]
@bd82 do you need any help to merge the package into Chevrotain? I can help you with that.

**Comment by bd82** [comment]
> do you need any help to merge the package into Chevrotain? I can help you with that.

@luiz290788 that would be awesome 👍 
Try to old add it as is right now with minimal changes, I will later try to convert it to TypeScript.

**Comment by luiz290788** [comment]
I've finally [started](https://github.com/Chevrotain/chevrotain/pull/1921) moving the package to inside chevrotain.

**Comment by bd82** [comment]
Hello @luiz290788 

regexp-to-ast is not part of the main Chevrotain repo.
You can re-create your PR there (its in typescript now) if you have free time.

Cheers.

**Pull request closed without merging**
